kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ppWQgwOVzT7Cdj4IY7JJkkeoH3+tcTVQGvbzlu5Zzvc=
      - identity: {}